// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsP08jiWllHTtAIKO7uHb-ghH3XgDvwOM',
    appId: '1:266663291106:web:78b6c897d9edfd39c956bb',
    messagingSenderId: '266663291106',
    projectId: 'gamemanagerapp-badc7',
    authDomain: 'gamemanagerapp-badc7.firebaseapp.com',
    storageBucket: 'gamemanagerapp-badc7.firebasestorage.app',
    measurementId: 'G-23RR0L1EHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFH3U0B6vF1VdQEFLA71YndKSjI65YxrY',
    appId: '1:266663291106:android:023a66036077e5e4c956bb',
    messagingSenderId: '266663291106',
    projectId: 'gamemanagerapp-badc7',
    storageBucket: 'gamemanagerapp-badc7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsP08jiWllHTtAIKO7uHb-ghH3XgDvwOM',
    appId: '1:266663291106:web:c47529f192676fe1c956bb',
    messagingSenderId: '266663291106',
    projectId: 'gamemanagerapp-badc7',
    authDomain: 'gamemanagerapp-badc7.firebaseapp.com',
    storageBucket: 'gamemanagerapp-badc7.firebasestorage.app',
    measurementId: 'G-Y00JEP54TK',
  );
}
